---
title: "Example Processing of an Orbitrap Iso file (.isox)"
description: >
  A minimal example for isotopocule data processing.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Loading and Processing Orbitrap Iso files}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(isoorbi)
```


```{r}
# Read .isox test data
file_path <-system.file("extdata", "testfile_Flow_Exploration_small.isox", package = "isoorbi")
df <- orbi_read_isox(file_path) 

# Keep only most important columns; equivalent to simplify check box in IsoX
df.simple <- orbi_simplify_isox(dataset = df)

# Filter the data
df.filtered <- df.simple %>% orbi_filter_isox(filename = c("s3744", "ac6"),
                                              time_min = 0.1, 
                                              time_max = 1, 
                                              compounds = c("HSO4-"),
                                              isotopocules = c("M0", "34S", "33S", "17O", "18O")) %>% 
                             orbi_filter_satellitePeaks() %>% 
                             orbi_filter_weak(min_percent = 10) %>% 
                             orbi_filter_TICxIT(truncate_extreme = 1)

# Define base peak and calculate the output table
df.output <- df.filtered %>% orbi_basepeak(basepeak = "M0") %>% 
                             orbi_calculate_results(ratio.method = "sum")

```
