---
title: "Example Processing of an Orbitrap Iso file (.isox)"
description: >
  A minimal example for usage of the function orbi_read_isox().
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Loading Orbitrap Iso files}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(isoorbi)
```


```{r}
# Read .isox test data
file_path <-system.file("extdata", "testfile_DualInlet_small.isox", package = "isoorbi")
df <- orbi_read_isox(file_path) 

# Keep only most important columns; equivalent to simplify check box in IsoX
df.simple <- orbi_simplify_isox(dataset = df)

# Filter the data
df.filtered <- df.simple %>% orbi_filter_isox(filename = "20220125_01",
                                              time_min = 0.1, 
                                              time_max = 5, 
                                              compounds = c("NO3-"),
                                              isotopocules = c("M0", "15N", "18O"),
                                              base_peak = "M0") %>% #FIXME
                             orbi_filter_satellitePeaks() %>% 
                             orbi_filter_weak(min_percent = 10) %>% 
                             orbi_filter_TICxIT(truncate_extreme = 1)

# Calculate output table
df.summary <- df.filtered %>% orbi_basepeak(basepeak = "15N") %>% #FIXME
                              orbi_calculate_output(ratio.method = "sum")

```
